"""Mechanical checks on references in the human-maintained documentation.

AGENTS.md routes an agent to whichever document is authoritative by citing
specific places. Documents are cited by anchor and code by symbol; both
survive edits above them and both fail loudly here when the thing they name
is renamed or removed. Line-number citations are rejected outright, because
they rot silently.

What this does not check is semantic drift: prose that is simply untrue
about the code. That is a reviewer's job.

Generated by agentify. The scanner lives in agentify.docs_refs; list build
products under `[docs] ignore_references` in .agentify.toml to exempt them.
"""

from pathlib import Path

from agentify.docs_refs import authoritative_docs, scan_docs
from agentify.repo import Repo

REPO = Repo.open(Path(__file__).resolve().parent.parent)


def test_the_router_is_among_the_authoritative_docs():
    # Guards against the list silently collapsing to nothing.
    assert REPO.path("AGENTS.md") in authoritative_docs(REPO)


def test_every_reference_resolves():
    unresolved = scan_docs(REPO)
    assert not unresolved, "\n".join(
        f"{u.doc}:{u.line}: `{u.ref}` -- {u.reason}" for u in unresolved
    )
